import { it, expect } from 'vitest';
import jwt from 'jsonwebtoken';
import NotificationService from '../src/services/NotificationService.js';
import PostService from '../src/services/PostService.js';
import CircleService from '../src/services/CircleService.js';
import ForumInteractionService from '../src/services/ForumInteractionService.js';
import { deleteAccount } from '../src/services/AccountService.js';
import { app } from '../src/server.js';
export function registerNotificationTests({ db, user, circle, getAdmin }) {
  const op = (a) => ({ accountId: a.id });
  const create = (a, c) => PostService.create(op(a), c.slug, { title: '通知标题', body: '不能放进通知的正文' });
  it('notifications: recipient isolation, unread filtering and idempotent reads, including pure admins', async () => {
    const c = await circle(), a = await user(), b = await user(), p = await create(a, c);
    await PostService.addComment(op(a), p.id, { body: '自回不通知' });
    expect((await NotificationService.unreadCount(op(a))).unreadCount).toBe(0);
    await PostService.addComment(op(b), p.id, { body: '评论不存快照' });
    const inbox = await NotificationService.list(op(a));
    expect(inbox).toMatchObject({ total: 1, unreadCount: 1 });
    expect(JSON.stringify(inbox)).not.toContain('评论不存快照');
    expect(JSON.stringify(inbox)).not.toContain('不能放进通知的正文');
    expect((await NotificationService.list(op(b))).total).toBe(0);
    for (const account of [b, getAdmin()]) await expect(NotificationService.markRead(op(account), inbox.data[0].id)).rejects.toMatchObject({ status: 404 });
    const first = await NotificationService.markRead(op(a), inbox.data[0].id);
    expect(first.readAt).toBeInstanceOf(Date);
    expect((await NotificationService.markRead(op(a), first.id)).readAt).toEqual(first.readAt);
    expect((await NotificationService.list(op(a), { filter: 'unread' })).total).toBe(0);
    expect((await NotificationService.unreadCount(op(a))).unreadCount).toBe(0);
    await expect(NotificationService.list(op(a), { filter: 'unknown' })).rejects.toMatchObject({ status: 400 });
    await expect(NotificationService.list(op(a), { page: '0' })).rejects.toMatchObject({ status: 400 });
    const adminPost = await create(getAdmin(), c);
    await PostService.addComment(op(b), adminPost.id, { body: '回复无志愿者档案的 admin' });
    expect((await NotificationService.list(op(getAdmin()))).data.some((n) => n.contextTitle === '通知标题')).toBe(true);
  });
  it('notifications: stable page ordering and comment targets beyond the first page', async () => {
    const c = await circle(), a = await user(), b = await user(), p = await create(a, c);
    let comment;
    for (let i = 0; i < 23; i++) comment = await PostService.addComment(op(b), p.id, { body: `分页评论${i}` });
    const first = await NotificationService.list(op(a)), second = await NotificationService.list(op(a), { page: '2' });
    expect(first.total).toBe(23); expect(first.count).toBe(20); expect(second.count).toBe(3);
    expect(new Set([...first.data, ...second.data].map((n) => n.id)).size).toBe(23);
    const last = first.data.find((n) => n.href.includes(comment.id));
    expect(last.href).toBe(`/forum/p/${p.id}?commentId=${comment.id}#comment-${comment.id}`);
    const located = await PostService.comments(op(a), p.id, { commentId: comment.id });
    expect(located.locatedCommentId).toBe(comment.id);
    expect(located.data.some((r) => r.id === comment.id)).toBe(true);
  });
  it('notifications: revalidate deleted/archived targets, keep generic moderation results, and suppress hidden replies', async () => {
    const c = await circle(), a = await user(), b = await user(), p = await create(a, c);
    const comment = await PostService.addComment(op(b), p.id, { body: '可删除评论' });
    await ForumInteractionService.mark(op(getAdmin()), p.id, 'feature', true);
    const featured = (await NotificationService.list(op(a))).data.find((n) => n.type === 'POST_FEATURED');
    await PostService.setDeleted(op(b), comment.id, true, true);
    expect((await NotificationService.list(op(a))).data.map((n) => n.type)).toEqual(['POST_FEATURED']);
    await PostService.setDeleted(op(getAdmin()), p.id, true);
    expect(await NotificationService.markRead(op(a), featured.id)).toMatchObject({ href: null, contextTitle: null, unavailableReason: '帖子已删除' });
    expect((await NotificationService.list(op(a))).data.every((n) => n.contextTitle === null)).toBe(true);
    await PostService.setDeleted(op(getAdmin()), p.id, false);
    await PostService.addComment(op(b), p.id, { body: '归档前回复' });
    await CircleService.setArchived(op(getAdmin()), c.id, true);
    const archived = await NotificationService.list(op(a));
    expect(archived.data.every((n) => n.type !== 'POST_COMMENT' && n.contextTitle === null && n.href === null && n.unavailableReason === '圈子已归档')).toBe(true);
    expect((await NotificationService.unreadCount(op(a))).unreadCount).toBe(archived.data.filter((n) => !n.readAt).length);
    await NotificationService.readAll(op(a), { viewedAt: archived.viewedAt.toISOString() });
    expect((await NotificationService.unreadCount(op(a))).unreadCount).toBe(0);
    await CircleService.setArchived(op(getAdmin()), c.id, false);
    expect((await NotificationService.list(op(a))).data.some((n) => n.type === 'POST_COMMENT')).toBe(false);
  });
  it('notifications: role links follow current permission and deleted actors are anonymized', async () => {
    const c = await circle(), a = await user(), owner = await user(), b = await user();
    await CircleService.setRole(op(getAdmin()), c.id, owner.id, 'OWNER');
    await CircleService.setRole(op(owner), c.id, a.id, 'STEWARD');
    const assigned = (await NotificationService.list(op(a))).data[0];
    expect(assigned.href).toBe(`/forum/c/${c.slug}/manage`);
    await CircleService.setRole(op(owner), c.id, a.id, 'STEWARD', true);
    expect((await NotificationService.markRead(op(a), assigned.id)).href).toBe(`/forum/c/${c.slug}`);
    await deleteAccount(owner.id);
    expect((await NotificationService.list(op(a))).data.every((n) => n.actor.name === '已注销' && n.actor.isDeleted)).toBe(true);
    const p = await create(a, c), comment = await PostService.addComment(op(b), p.id, { body: '受管理的评论' });
    await PostService.setDeleted(op(getAdmin()), comment.id, true, true);
    const removed = (await NotificationService.list(op(b))).data[0];
    expect(removed).toMatchObject({ summary: '删除了你的评论', contextTitle: null, href: null, unavailableReason: '评论已删除' });
    await db.account.update({ where: { id: b.id }, data: { isActive: false } });
    await expect(NotificationService.list(op(b))).rejects.toMatchObject({ status: 401 });
  });
  it('notifications: read-all respects inclusive viewing cutoff, recipient boundary and future clamp', async () => {
    const c = await circle(), a = await user(), b = await user(), p = await create(a, c);
    await PostService.addComment(op(b), p.id, { body: '旧回复' });
    const inbox = await NotificationService.list(op(a)), cutoff = inbox.viewedAt;
    await db.notification.update({ where: { id: inbox.data[0].id }, data: { createdAt: cutoff } });
    const reply = await PostService.addComment(op(b), p.id, { body: '新回复' });
    const later = await db.notification.findFirst({ where: { targetId: reply.id, type: 'POST_COMMENT' } });
    await db.notification.update({ where: { id: later.id }, data: { createdAt: new Date(cutoff.getTime() + 1) } });
    await CircleService.setRole(op(getAdmin()), c.id, b.id, 'STEWARD');
    expect((await NotificationService.readAll(op(a), { viewedAt: cutoff.toISOString() })).updatedCount).toBe(1);
    expect((await db.notification.findUnique({ where: { id: later.id } })).readAt).toBeNull();
    expect((await NotificationService.unreadCount(op(b))).unreadCount).toBe(1);
    expect((await NotificationService.readAll(op(a), { viewedAt: cutoff.toISOString() })).updatedCount).toBe(0);
    await db.notification.update({ where: { id: later.id }, data: { createdAt: new Date('2099-01-01T00:00:00Z') } });
    await NotificationService.readAll(op(a), { viewedAt: '2199-01-01T00:00:00Z' });
    expect((await db.notification.findUnique({ where: { id: later.id } })).readAt).toBeNull();
    for (const viewedAt of [undefined, 123, 'bad', '2026-99-99T00:00:00Z']) await expect(NotificationService.readAll(op(a), { viewedAt })).rejects.toMatchObject({ status: 400 });
  });
  it('notifications HTTP: authentication, no-store, ownership on writes and account spoofing rejection', async () => {
    const c = await circle(), a = await user(), b = await user(), p = await create(a, c);
    await PostService.addComment(op(b), p.id, { body: 'HTTP 边界' });
    const own = (await NotificationService.list(op(a))).data[0];
    const server = await new Promise((resolve) => { const s = app.listen(0, '127.0.0.1', () => resolve(s)); });
    const root = `http://127.0.0.1:${server.address().port}/api/v1/notifications`;
    const headers = { Authorization: `Bearer ${jwt.sign({ sub: b.id }, process.env.JWT_SECRET, { expiresIn: '5m' })}`, 'Content-Type': 'application/json' };
    try {
      expect((await fetch(root)).status).toBe(401);
      const response = await fetch(`${root}?recipientId=${a.id}`, { headers });
      expect(response.headers.get('cache-control')).toContain('no-store');
      expect((await response.json()).total).toBe(0);
      expect((await fetch(`${root}/${own.id}/read`, { method: 'PATCH', headers, body: JSON.stringify({ recipientId: a.id }) })).status).toBe(404);
      expect((await fetch(`${root}/read-all`, { method: 'POST', headers, body: '{}' })).status).toBe(400);
      await fetch(`${root}/read-all`, { method: 'POST', headers, body: JSON.stringify({ recipientId: a.id, viewedAt: new Date().toISOString() }) });
      expect((await NotificationService.unreadCount(op(a))).unreadCount).toBe(1);
    } finally { await new Promise((resolve) => { server.close(resolve); server.closeAllConnections(); }); }
  });
}
