import { test, expect } from 'playwright/test';

async function login(page, email = 'training-admin@example.test', destination = '/training') {
  await page.goto('/training');
  await page.getByLabel('邮箱 / 手机号 / 志愿者 ID').fill(email);
  await page.getByLabel('密码', { exact: true }).fill('TestOnly@123');
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await expect(page.getByRole('button', { name: '退出登录', exact: true }).first()).toBeVisible();
  await page.goto(destination);
  if (destination === '/training') await expect(page.getByRole('heading', { name: '培训考勤', exact: true })).toBeVisible();
}

test.describe.serial('training and ordinary labels', () => {
  let sessionUrl;
  test('desktop: plain-name paste, append, edit, remove and restore', async ({ page }) => {
    const errors = []; page.on('pageerror', (e) => errors.push(e.message));
    await login(page);
    await page.getByRole('button', { name: '新建培训', exact: true }).click();
    const dialog = page.getByRole('dialog');
    await dialog.getByLabel('培训名称').fill('九月笔译基础培训');
    await dialog.getByLabel('受训类型').selectOption({ label: '培训测试部门甲 · 笔译受训' });
    await dialog.getByLabel('培训日期').fill('2026-09-15');
    await dialog.getByLabel('培训内容').fill('从文本理解到译稿校对，交流翻译实践中的方法与心得。');
    await dialog.getByRole('button', { name: '创建培训', exact: true }).click();
    await expect(page).toHaveURL(/\/training\/.+/);
    sessionUrl = new URL(page.url()).pathname;
    await page.getByLabel('粘贴姓名名单').fill('张三\n李四\n未登记人员');
    await expect(page.getByRole('button', { name: '加入已匹配的 2 人' })).toBeEnabled();
    await page.getByRole('button', { name: '加入已匹配的 2 人' }).click();
    await expect(page.getByText('已新增 2 人，已有 0 人跳过。')).toBeVisible();
    await expect(page.getByLabel('粘贴姓名名单')).toHaveValue('未登记人员');
    await page.getByRole('tab', { name: '搜索添加', exact: true }).click();
    await page.getByLabel('搜索参加人员').fill('王五');
    await page.getByRole('button', { name: '添加', exact: true }).click();
    await page.getByRole('button', { name: '加入已匹配的 1 人' }).click();
    await expect(page.getByText('已新增 1 人，已有 0 人跳过。')).toBeVisible();
    await page.getByLabel('编辑培训信息').click();
    await page.getByRole('dialog').getByLabel('时长 / 小时').fill('3');
    await page.getByRole('button', { name: '预览修改', exact: true }).click();
    await expect(page.getByText('将同步更新 3 人的有效考勤')).toBeVisible();
    await page.getByRole('button', { name: '确认同步保存', exact: true }).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await page.getByRole('button', { name: '移除', exact: true }).first().click();
    await page.getByRole('button', { name: '确认移除', exact: true }).click();
    await page.getByRole('button', { name: '已移除 1' }).click();
    await page.getByRole('button', { name: '恢复', exact: true }).click();
    await page.getByRole('button', { name: '确认恢复', exact: true }).click();
    await page.getByRole('button', { name: '当前名单', exact: true }).click();
    await expect(page.getByRole('button', { name: '移除', exact: true })).toHaveCount(3);
    await page.getByLabel('搜索参加人员').fill('');
    await page.getByRole('tab', { name: '粘贴名单', exact: true }).click();
    await page.getByLabel('粘贴姓名名单').fill('');
    await page.evaluate(() => { document.activeElement?.blur(); window.scrollTo(0, 0); });
    await page.screenshot({ path: '/tmp/volunteer-training-desktop.png', fullPage: true });
    await page.setViewportSize({ width: 1920, height: 1080 });
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.screenshot({ path: '/tmp/volunteer-training-wide.png', fullPage: true });
    expect(errors).toEqual([]);
  });
  test('mobile: readable stacked layout and name lookup without horizontal overflow', async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 });
    await login(page); await page.goto(sessionUrl);
    await expect(page.getByRole('heading', { name: '九月笔译基础培训', exact: true })).toBeVisible();
    await page.getByLabel('粘贴姓名名单').fill('张三');
    await expect(page.getByText('已在名单', { exact: true })).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.evaluate(() => { document.activeElement?.blur(); window.scrollTo(0, 0); });
    await page.screenshot({ path: '/tmp/volunteer-training-mobile.png', fullPage: true });
  });
  test('labels: cross-category selection, record association, direct links and safe unlink', async ({ page }) => {
    await login(page); await page.goto('/tags');
    await page.getByRole('button', { name: '新建标签组', exact: true }).click();
    const dialog = page.getByRole('dialog');
    await dialog.getByLabel('标签组名称').fill('合作方式');
    await dialog.getByLabel('说明', { exact: true }).fill('记录伙伴们如何一起完成服务。');
    await dialog.getByRole('button', { name: '项目支持', exact: true }).click();
    await dialog.getByLabel('普通服务', { exact: true }).check();
    await dialog.getByRole('button', { name: '项目管理', exact: true }).click();
    await dialog.getByLabel('协调服务', { exact: true }).check();
    await dialog.getByRole('button', { name: '项目支持', exact: true }).click();
    await expect(dialog.getByLabel('普通服务', { exact: true })).toBeChecked();
    await expect(dialog.getByText('已选 2 项')).toBeVisible();
    await dialog.getByRole('button', { name: '保存标签组', exact: true }).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    const group = page.locator('section').filter({ has: page.getByRole('heading', { name: '合作方式', exact: true }) });
    await group.getByRole('button', { name: '添加标签', exact: true }).click();
    await page.getByRole('dialog').getByLabel('标签名称').fill('共同完成');
    await page.getByRole('dialog').getByRole('button', { name: '保存', exact: true }).click();
    await expect(page.getByRole('heading', { name: '共同完成', exact: true })).toBeVisible();
    const tagUrl = new URL(page.url()).pathname;
    await page.getByRole('button', { name: '关联记录', exact: true }).click();
    await page.getByLabel('查找可关联记录').fill('张三');
    await page.getByRole('dialog').getByRole('button', { name: '关联', exact: true }).first().click();
    await page.getByRole('dialog').getByRole('button', { name: '完成', exact: true }).click();
    await expect(page.getByRole('button', { name: '解除关联', exact: true })).toHaveCount(1);
    const recordLink = page.locator('a[href^="/records/"]').first();
    const recordPath = await recordLink.getAttribute('href');
    await page.evaluate(() => { document.activeElement?.blur(); window.scrollTo(0, 0); });
    await page.screenshot({ path: '/tmp/volunteer-tags-desktop.png', fullPage: true });
    await recordLink.click();
    await expect(page.getByText('服务记录', { exact: true })).toBeVisible();
    await page.goto(tagUrl); await page.getByRole('button', { name: '解除关联', exact: true }).click();
    await page.getByRole('dialog').getByRole('button', { name: '确认', exact: true }).click();
    await expect(page.getByRole('button', { name: '解除关联', exact: true })).toHaveCount(0);
    await page.goto(recordPath); await expect(page.getByText('服务记录', { exact: true })).toBeVisible();
    await page.setViewportSize({ width: 390, height: 844 }); await page.goto(tagUrl);
    await expect(page.getByRole('heading', { name: '共同完成', exact: true })).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.evaluate(() => { document.activeElement?.blur(); window.scrollTo(0, 0); });
    await page.screenshot({ path: '/tmp/volunteer-tags-mobile.png', fullPage: true });
  });
  test('member: submit a tagged record, edit its service item and view protected training attendance', async ({ page }) => {
    await login(page, 'training-1@example.test', '/me');
    await page.getByRole('button', { name: '提交项目服务', exact: true }).click();
    const dialog = page.getByRole('dialog');
    await dialog.getByRole('tab', { name: /项目支持/ }).click();
    await dialog.getByRole('button', { name: '普通服务', exact: true }).click();
    await dialog.getByRole('button', { name: '共同完成', exact: true }).click();
    await dialog.getByLabel('服务日期').fill('2026-09-16');
    await dialog.getByLabel('描述').fill('浏览器验收：一起完成翻译和校对工作。');
    await dialog.getByRole('button', { name: '提交', exact: true }).click();
    await expect(dialog).toHaveCount(0);
    await page.getByRole('button', { name: /^普通服务:/ }).click();
    const card = page.locator('div.rounded-xl.border').filter({ has: page.getByText('浏览器验收：一起完成翻译和校对工作。', { exact: true }) }).last();
    await expect(card.getByRole('link', { name: '共同完成', exact: true })).toBeVisible();
    await card.getByRole('button', { name: '编辑', exact: true }).click();
    const edit = page.getByRole('dialog', { name: '编辑服务记录', exact: true });
    await edit.getByRole('combobox', { name: '服务项', exact: true }).selectOption({ label: '项目管理 · 协调服务' });
    await edit.getByRole('button', { name: '保存', exact: true }).click();
    await expect(edit).toHaveCount(0);
    await page.getByRole('dialog').getByRole('button', { name: '关闭', exact: true }).click();
    await page.getByRole('button', { name: /^协调服务:/ }).click();
    await expect(card.getByText(/协调服务/)).toBeVisible();
    await page.getByRole('dialog').getByRole('button', { name: '关闭', exact: true }).click();
    await page.getByRole('button', { name: /^笔译受训:/ }).click();
    const attendance = page.locator('div.rounded-xl.border').filter({ has: page.getByText('从文本理解到译稿校对，交流翻译实践中的方法与心得。', { exact: true }) }).last();
    await expect(attendance).toBeVisible();
    await expect(attendance.getByRole('button', { name: '编辑', exact: true })).toHaveCount(0);
    await expect(attendance.getByRole('button', { name: '删除', exact: true })).toHaveCount(0);
  });
});
